CREATE DATABASE IF NOT EXISTS db_servicio;
USE db_servicio;

-- ENTIDAD DE LA CATEGORIA.
CREATE TABLE IF NOT EXISTS CATEGORIA (
  idCATEGORIA CHAR(36) NOT NULL ,
  descripcion VARCHAR(45) NOT NULL UNIQUE,
  esServicio INT NULL DEFAULT 0,
  PRIMARY KEY(idCATEGORIA)
) 
ENGINE = InnoDB;

-- ENTIDAD DEL EQUIPO
CREATE TABLE  IF NOT EXISTS EQUIPO(
  idequipo CHAR(36) NOT NULL,
  nombreequipo VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY(idequipo)
)

-- ENTIDAD DE LA MARCA
CREATE TABLE  IF NOT EXISTS MARCA(
  idMarca CHAR(36) NOT NULL,
  nombre VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY(idMarca)
)
